- restConfiguration:
    apiContextPath: /api-doc
    #bindingMode: json
    #bindingPackageScan: ${{ values.java_package_domain }}.${{ values.java_group_name }}.${{ values.java_package_name }}.model

- rest:
    id: rest-openapi
    openApi:
      id: openapi-configuration
      specification: https://raw.githubusercontent.com/contract-first-idp/${{ values.api_id }}/main/specification.yaml
      missingOperation: ignore